freebsd_instance:
  image_family: freebsd-13-0-snap

task:
  env:
    matrix:
      - LISP: sbcl
      - LISP: ccl
      - LISP: clisp
  preinstall_script:
    - pkg install -y curl
  install_script:
    - curl -L https://raw.githubusercontent.com/shamazmazum/cl-cirrus/master/install.sh | sh
  script:
    - cl -f $CIRRUS_WORKING_DIR/tests/travis.lisp
