dist: bionic
language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp
    - LISP=abcl
    - LISP=ecl

install:
  - sudo apt-get install info install-info
  - curl -L https://raw.githubusercontent.com/lispci/cl-travis/master/install.sh | sh

script:
  - cl -f $TRAVIS_BUILD_DIR/tests/travis.lisp
